package netlight.com.helloandroid;

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

/**
 * Created by Alexander Cyon on 21/01/15.
 */
public class LoginEntry {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;

    @DatabaseField
    long userId; // This is the id of the user that the login entry is for

    @DatabaseField
    Date date;

    // empty constructor needed by OrmLite
    public LoginEntry() {
    }

    public LoginEntry(long userId, Date date) {
        this.userId = userId;
        this.date = date;
    }

    // Convenience constructor using the current time
    public LoginEntry(long userId) {
        this(userId, new Date());
    }

    public long getId() {
        return id;
    }

    public long getUserId() {
        return userId;
    }

    public Date getDate() {
        return date;
    }
}
